### ISSUE TITLE
Добавить проверку на наличие файла

### ISSUE THREAD

**Issue by anry-das** [ValentynChepiha/NCTaskManager#10]
Нужно Добавить проверку на наличие файла перед чтением (например, в TaskIO.readBinary), чтобы предотвратить появление сообщения об ошибке.

**Comment by ValentynChepiha** [comment]
Виправив 
c86749c

**Comment by ValentynChepiha** [comment]
Добавил
https://github.com/ValentynChepiha/NCTaskManager/issues/10

пт, 14 січ. 2022 р. о 11:11 Andrey Denysenko ***@***.***>
пише:
