### ISSUE TITLE
Переместить ModalWindow в пакет view

### ISSUE THREAD

**Issue by anry-das** [ValentynChepiha/NCTaskManager#11]
Переместить ModalWindow в пакет view т.к. он относится к представлению

**Comment by ValentynChepiha** [comment]
Переместил
aa50c8d

**Comment by ValentynChepiha** [comment]
Исправил
https://github.com/ValentynChepiha/NCTaskManager/issues/11

пт, 14 січ. 2022 р. о 11:11 Andrey Denysenko ***@***.***>
пише:
