### ISSUE TITLE
[REAFCTORING] Рефакторинг TasksForm и создание контроллера приложения

### ISSUE THREAD

**Issue by anry-das** [ValentynChepiha/NCTaskManager#12]
Сласс TasksForm слишком большое. Его необходимо разбить на меньшие классы.
На данный момент в приложении отсутствует выделенный контроллер. Необходимо его создать.
Для этого:
- создать пакет cintroller и класс в нем
- вынести в новый класс все методы из TasksForm, которые не относятся к view
Например, initTaskList() - это контроллер, а initialize() - это представление (но его нужно разбить на более мелкие методы).

**Comment by ValentynChepiha** [comment]
Разбил контроллер 
e92ea0f
